using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SVGHelper.Model.Svg
{
    /// <summary>
    /// List of color keywords.
    /// CSS2 defined 16 keywords.
    /// User Preferences for color (system).
    /// </summary>
    public enum EBDTSvgAttributeColor
    {
        NONE,

        /// <summary>
        /// <see href="https://www.w3.org/TR/2008/REC-CSS2-20080411/syndata.html#value-def-color"/>
        /// </summary>
        CSS2_AQUA,
        CSS2_BLACK,
        CSS2_BLUE,
        CSS2_FUCHSIA,
        CSS2_GRAY,
        CSS2_GREEN,
        CSS2_LIME,
        CSS2_MAROON,
        CSS2_NAVY,
        CSS2_OLIVE,
        CSS2_PURPLE,
        CSS2_RED,
        CSS2_SILVER,
        CSS2_TEAL,
        CSS2_WHITE,
        CSS2_YELLOW,

        /// <summary>
        /// <see href="https://www.w3.org/TR/2008/REC-CSS2-20080411/ui.html#system-colors"/>
        /// </summary>
        SYSTEM_ACTIVEBORDER,
        SYSTEM_ACTIVECAPTION,
        SYSTEM_APPWORKSPACE,
        SYSTEM_BACKGROUND,
        SYSTEM_BUTTONFACE,
        SYSTEM_BUTTONHIGHLIGHT,
        SYSTEM_BUTTONSHADOW,
        SYSTEM_BUTTONTEXT,
        SYSTEM_CAPTIONTEXT,
        SYSTEM_GRAYTEXT,
        SYSTEM_HIGHLIGHT,
        SYSTEM_HIGHLIGHTTEXT,
        SYSTEM_INACTIVEBORDER,
        SYSTEM_INACTIVECAPTION,
        SYSTEM_INACTIVECAPTIONTEXT,
        SYSTEM_INFOBACKGROUND,
        SYSTEM_INFOTEXT,
        SYSTEM_MENU,
        SYSTEM_MENUTEXT,
        SYSTEM_SCROLLBAR,
        SYSTEM_THREEDDARKSHADOW,
        SYSTEM_THREEDFACE,
        SYSTEM_THREEDHIGHLIGHT,
        SYSTEM_THREEDLIGHTSHADOW,
        SYSTEM_THREEDSHADOW,
        SYSTEM_WINDOW,
        SYSTEM_WINDOWFRAME,
        SYSTEM_WINDOWTEXT,

        /// <summary>
        /// <see href="https://www.w3.org/TR/SVG/types.html#ColorKeywords"/>
        /// </summary>
        SVG_ALICEBLUE,
        SVG_ANTIQUEWHITE,
        SVG_AQUA,
        SVG_AQUAMARINE,
        SVG_AZURE,
        SVG_BEIGE,
        SVG_BISQUE,
        SVG_BLACK,
        SVG_BLANCHEDALMOND,
        SVG_BLUE,
        SVG_BLUEVIOLET,
        SVG_BROWN,
        SVG_BURLYWOOD,
        SVG_CADETBLUE,
        SVG_CHARTREUSE,
        SVG_CHOCOLATE,
        SVG_CORAL,
        SVG_CORNFLOWERBLUE,
        SVG_CORNSILK,
        SVG_CRIMSON,
        SVG_CYAN,
        SVG_DARKBLUE,
        SVG_DARKCYAN,
        SVG_DARKGOLDENROD,
        SVG_DARKGRAY,
        SVG_DARKGREEN,
        SVG_DARKGREY,
        SVG_DARKKHAKI,
        SVG_DARKMAGENTA,
        SVG_DARKOLIVEGREEN,
        SVG_DARKORANGE,
        SVG_DARKORCHID,
        SVG_DARKRED,
        SVG_DARKSALMON,
        SVG_DARKSEAGREEN,
        SVG_DARKSLATEBLUE,
        SVG_DARKSLATEGRAY,
        SVG_DARKSLATEGREY,
        SVG_DARKTURQUOISE,
        SVG_DARKVIOLET,
        SVG_DEEPPINK,
        SVG_DEEPSKYBLUE,
        SVG_DIMGRAY,
        SVG_DIMGREY,
        SVG_DODGERBLUE,
        SVG_FIREBRICK,
        SVG_FLORALWHITE,
        SVG_FORESTGREEN,
        SVG_FUCHSIA,
        SVG_GAINSBORO,
        SVG_GHOSTWHITE,
        SVG_GOLD,
        SVG_GOLDENROD,
        SVG_GRAY,
        SVG_GREY,
        SVG_GREEN,
        SVG_GREENYELLOW,
        SVG_HONEYDEW,
        SVG_HOTPINK,
        SVG_INDIANRED,
        SVG_INDIGO,
        SVG_IVORY,
        SVG_KHAKI,
        SVG_LAVENDER,
        SVG_LAVENDERBLUSH,
        SVG_LAWNGREEN,
        SVG_LEMONCHIFFON,
        SVG_LIGHTBLUE,
        SVG_LIGHTCORAL,
        SVG_LIGHTCYAN,
        SVG_LIGHTGOLDENRODYELLOW,
        SVG_LIGHTGRAY,
        SVG_LIGHTGREEN,
        SVG_LIGHTGREY,
        SVG_LIGHTPINK,
        SVG_LIGHTSALMON,
        SVG_LIGHTSEAGREEN,
        SVG_LIGHTSKYBLUE,
        SVG_LIGHTSLATEGRAY,
        SVG_LIGHTSLATEGREY,
        SVG_LIGHTSTEELBLUE,
        SVG_LIGHTYELLOW,
        SVG_LIME,
        SVG_LIMEGREEN,
        SVG_LINEN,
        SVG_MAGENTA,
        SVG_MAROON,
        SVG_MEDIUMAQUAMARINE,
        SVG_MEDIUMBLUE,
        SVG_MEDIUMORCHID,
        SVG_MEDIUMPURPLE,
        SVG_MEDIUMSEAGREEN,
        SVG_MEDIUMSLATEBLUE,
        SVG_MEDIUMSPRINGGREEN,
        SVG_MEDIUMTURQUOISE,
        SVG_MEDIUMVIOLETRED,
        SVG_MIDNIGHTBLUE,
        SVG_MINTCREAM,
        SVG_MISTYROSE,
        SVG_MOCCASIN,
        SVG_NAVAJOWHITE,
        SVG_NAVY,
        SVG_OLDLACE,
        SVG_OLIVE,
        SVG_OLIVEDRAB,
        SVG_ORANGE,
        SVG_ORANGERED,
        SVG_ORCHID,
        SVG_PALEGOLDENROD,
        SVG_PALEGREEN,
        SVG_PALETURQUOISE,
        SVG_PALEVIOLETRED,
        SVG_PAPAYAWHIP,
        SVG_PEACHPUFF,
        SVG_PERU,
        SVG_PINK,
        SVG_PLUM,
        SVG_POWDERBLUE,
        SVG_PURPLE,
        SVG_RED,
        SVG_ROSYBROWN,
        SVG_ROYALBLUE,
        SVG_SADDLEBROWN,
        SVG_SALMON,
        SVG_SANDYBROWN,
        SVG_SEAGREEN,
        SVG_SEASHELL,
        SVG_SIENNA,
        SVG_SILVER,
        SVG_SKYBLUE,
        SVG_SLATEBLUE,
        SVG_SLATEGRAY,
        SVG_SLATEGREY,
        SVG_SNOW,
        SVG_SPRINGGREEN,
        SVG_STEELBLUE,
        SVG_TAN,
        SVG_TEAL,
        SVG_THISTLE,
        SVG_TOMATO,
        SVG_TURQUOISE,
        SVG_VIOLET,
        SVG_WHEAT,
        SVG_WHITE,
        SVG_WHITESMOKE,
        SVG_YELLOW,
        SVG_YELLOWGREEN,
    }
}
